[api]
enabled = true
port = 3011
host = "0.0.0.0"
tls = false

[gateway]
enabled = true
port = 3012
host = "0.0.0.0"
tls = false

[general]
server_domain = "localhost"

[general.database]
max_connections = 20
database = "sonata"
username = "sonata"
password = "sonata"
port = 5432
host = "localhost"
tls = "prefer"
