name: pre-commit

on:
  pull_request:
  push:
    branches: ["*"]

# Auto-abort duplicate jobs (e.g. job being triggered again on push to open PR)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
        with:
          cache-all-crates: "true"
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: "rustfmt"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
          components: "rustfmt"
      - name: Setup PostgreSQL for Linux/macOS/Windows
        uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres
        with:
          postgres-version: 17
      - name: "Install dependencies, prepare database"
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
        run: |
          cargo install -f -q sqlx-cli
          cargo sqlx migrate run
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: pre-commit/action@576ff52938d158a24ac7e009dfa94b1455e7df99
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
